apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: com-clean-dev
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: toor
  MARIADB_DATABASE: clean_dev
  MARIADB_USER: user
  MARIADB_PASSWORD: user@123
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: com-clean-dev
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306
      protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: com-clean-dev
spec:
  serviceName: mariadb
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_DATABASE
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mariadb-pvc
