apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: com-clean-dev
spec:
  type: NodePort
  selector:
    app: mariadb        
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306   
